### ISSUE TITLE
Failing tests in test_stats_sp.test_tsboxplot

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#302] opened 2015-05-05 14:19 UTC
On some mac boxes [see http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-osx-10.6/builds/276/steps/shell_5/logs/stdio] two tests fail.

As in #229, tests on NeuroDebian fail with recent numpy/scipy but not with older versions:
fail: numpy 1.10.0.dev0+63e8bab and scipy 0.16.0.dev0+1306448
pass: numpy 1.6.2 and scipy 0.10.0.

(Note: numpy is reported as an "older" version even though I pulled straight from git://github.com/numpy/numpy/git and then compiled & installed)

@yarikoptic @hanke For now I added this to the Release 2.4 milestone, I hope you agree?
```
FAIL: mvpa2.tests.test_stats.test_tsboxplot
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/mvpa2/tests/test_stats.py", line 175, in test_tsboxplot
    assert_equal(outlier.mask.sum(), np.prod(outlier.shape) - 1)
AssertionError: 18 != 19

 ======================================================================
FAIL: mvpa2.tests.test_stats_sp.test_tsboxplot
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/mvpa2/tests/test_stats.py", line 175, in test_tsboxplot
    assert_equal(outlier.mask.sum(), np.prod(outlier.shape) - 1)
AssertionError: 18 != 19
```

**Comment by yarikoptic** [comment] 2015-05-06 01:53
it seems that similar issues now detected on Windows (thanks to mathew brett for fixing up for my recent addition of installing statsmodels which caused some havoc):
http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-win32/builds/111/steps/shell_5/logs/stdio

**Comment by nno** [comment] 2015-05-06 07:00
PR #304 tries to address this.

**Comment by hanke** [comment] 2015-05-06 07:57
All the fixes seem to be merged now. Let's wait for buildbot.

**Comment by hanke** [comment] 2015-05-06 08:13
Oi -- it has changed.

````
======================================================================
ERROR: mvpa2.tests.test_fxmapper.test_mean_removal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_fxmapper.py", line 308, in test_mean_removal
    mr(random_array.copy())))
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\base\learner.py", line 259, in __call__
    return super(Learner, self).__call__(ds)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\base\node.py", line 121, in __call__
    result = self._call(ds)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\mappers\base.py", line 263, in _call
    return self.forward(ds)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-winT: MVPA_SEED=1648271818
T: Skipping testing of all dependencies since verbosity (MVPA_TESTS_VERBOSITY) is too low
T: MVPA_SEED=1648271818
T: Skipping testing of all dependencies since verbosity (MVPA_TESTS_VERBOSITY) is too low
32\build\venv\lib\site-packages\mvpa2\mappers\base.py", line 197, in forward
    return self._forward_data(data)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\mappers\fx.py", line 671, in _forward_data
    mdata = mdata - mean[:, np.newaxis]
MemoryError

======================================================================
FAIL: test_surf_voxel_selection (mvpa2.tests.test_surfing.SurfTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_surfing.py", line 779, in test_surf_voxel_selection
    assert_true('imghdr' in dset_.a.keys())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 462 tests in 325.791s

````

**Comment by hanke** [comment] 2015-05-06 08:20
Cannot reproduce any of them locally on Debian. :(

**Comment by nno** [comment] 2015-05-06 12:11
mvpa2/tests/test_fxmapper.py lines 306:310:
```
    random_array = np.random.rand(50, 1000000)
    assert_true(np.array_equal(mr_fx(random_array.copy()),
                               mr(random_array.copy())))
    assert_true(np.array_equal(mr_fx(random_array.copy()),
                               mr_inplace(random_array.copy())))
```
which may explain the MemoryError? I noticed that running this tests takes a long time on Neurodebian when not much memory is available.

@yoh @hanke, do you see a particular reason why the array has to be so big? Can't we just use a tiny array here?

**Comment by hanke** [comment] 2015-05-06 12:19
@nno good catch -- looking into it.

**Comment by yarikoptic** [comment] 2015-05-06 12:20
@hanke if needed -- we have Windows VM running on smaug... just login as datalad and attach VNC to 2nd display
not sure thought about dependencies for PyMVPA - but should be installable with virtualenv+pip

**Comment by hanke** [comment] 2015-05-06 13:22
First fix worked. Remaining:

````
======================================================================
FAIL: test_surf_voxel_selection (mvpa2.tests.test_surfing.SurfTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_surfing.py", line 779, in test_surf_voxel_selection
    assert_true('imghdr' in dset_.a.keys())
AssertionError: False is not true
````

**Comment by nno** [comment] 2015-05-06 15:01
Any idea how to reproduce this error? It runs fine on OSX 10.9 and Neurodebian; for the latter with both standard and very latest numpy / scipy.

Looking in this test, the core code is 
``` 
                    dset1 = dset.copy()
                    dset1.fa['dset'] = [1]
                    dset2 = dset.copy()
                    dset2.fa['dset'] = [2]              
                    dset_ = hstack((dset1, dset2), 'drop_nonunique')
                    dset_.sa = dset1.sa
                    assert_true('imghdr' in dset_.a.keys())
```
and then the test fails if 'imghdr' is not present in dset_.

Thus, for some reason, hstack thinks that dset1.a['imghdr'] is not equal to dset2.a['imghdr'].

**Comment by yarikoptic** [comment] 2015-05-06 15:09
@nno, @hanke  if no easy ways to reproduce -- let me ask matthew about access to that box and troubleshoot in place

**Comment by nno** [comment] 2015-05-07 09:47
@yoh, any progress on this issue?

**Comment by nno** [comment] 2015-05-07 09:47
@yarikoptic any updates on this issue?

**Comment by yarikoptic** [comment] 2015-05-07 13:41
ok -- thanks to Matthew got access to the box, troubleshooting now -- there is indeed no imghdr in a

**Comment by yarikoptic** [comment] 2015-05-07 14:15
ok -- the reason is that we got "nan"s in `scl_slope` and `scl_inter` in the header of our created Nifti1Image's header, while using nibabel 2.0.0 on that windows buildbot.  Locally I do not see nans with nibabel 2.0.0.  

@matthew-brett : any straight ideas one why we are getting nans?  here is a protocol of struggle:
http://www.onerussian.com/tmp/gkrellShoot_05-07-15_101412.png  (you know where taht window lives so you are welcome to connect)

in our case -- we could skip the test and/or issue the warning... or fix up for that in fmri_dataset (if both of those nan -- assign proper values 1.0,0)?

**Comment by yarikoptic** [comment] 2015-05-07 14:30
ok -- so we just wrap it up for now -- I will add taht guarding into fmri_dataset with a warning being issued.

**Comment by yarikoptic** [comment] 2015-05-08 02:21
imghdr issue was fixed, so closing

**Closed by yarikoptic** 2015-05-08 02:21 UTC
