### ISSUE TITLE
Wrong GNB probabilities

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#581] opened 2018-04-29 13:37 UTC
Reported on the mailing list by Richard Dinga

```
Thanks, this seems to be the solution according to documentation, but it doesn't work for my data. Here is an example using tutorial data:

from mvpa2.suite import *
datapath = '/usr/share/data/pymvpa2-tutorial/'
haxby = load_tutorial_data(datapath,
        roi='vt',
        add_fa={'vt_thr_glm': os.path.join(datapath, 'haxby2001',
                                           'sub001', 'masks',
                                                     'orig', 'vt.nii.gz')})
poly_detrend(haxby, polyord=1, chunks_attr='chunks')
haxby = haxby[np.array([l in ['rest', 'house', 'face']
                           for l in haxby.targets], dtype='bool')]
zscore(haxby, chunks_attr='chunks', param_est=('targets', ['rest']), 
       dtype='float32')
haxby = haxby[haxby.sa.targets != 'rest']
haxby = remove_invariant_features(haxby)

clf = GNB(enable_ca='estimates', logprob=True, normalize=True)
cv = CrossValidation(clf, NFoldPartitioner(attr='chunks'), postproc=None)
cv_results = cv(haxby)
print clf.ca.estimates

[[          inf           inf]
 [-234.34792494    0.        ]
 [          inf           inf]
 ..., 
 [          inf           inf]
 [          inf           inf]
 [          inf           inf]]

However it works with test data:

from mvpa2.testing.datasets import *
ds_test = datasets['uni2medium']
cv_results = cv(ds_test)
print np.round(np.exp(clf.ca.estimates), 3)

[[ 0.956  0.044]
 [ 1.     0.   ]
 [ 1.     0.   ]
 ..., 
 [ 0.     1.   ]
 [ 0.168  0.832]
 [ 0.001  0.999]]
```

**Comment by dinga92** [comment] 2018-04-30 10:28
Thanks for looking at this, although it seems to work fine when doing searchlight (in terms of errors, not the probabilities, I don't know how to access them)

**Comment by yarikoptic** [comment] 2018-04-30 14:11
@dinga92   uff -- you got me worried for a second.  The culprit which I have missed is in the difference of your `print` statements ;)  
`print clf.ca.estimates` vs `print np.round(np.exp(clf.ca.estimates), 3)` ;-)

For searchlights if you want we could make it work -- just would need a little helper to get them out and place as the result

**Comment by dinga92** [comment] 2018-04-30 15:51
what do you mean? I rounded the good ones, just so I am not dealing with the scientific notation, (although  np.set_printoptions(suppress=True) would be a better option), but in the haxby case, they are still inf aren't they? Or am I missing something super trivial?

**Comment by yarikoptic** [comment] 2018-04-30 16:55
`np.exp` in one print but not the other... ?

**Comment by dinga92** [comment] 2018-04-30 17:18
exp inf is still inf. and problem is visible with and without exponentiation. With `logprob=True', the outputed logprobs are very small, which after exponentiation produce 0 or nan.

    clf = GNB(enable_ca='estimates', logprob=True, normalize=True)
    cv = CrossValidation(clf, NFoldPartitioner(attr='chunks'), postproc=None)
    cv_results = cv(haxby)
    print clf.ca.estimates
    print np.exp(clf.ca.estimates)
    
    np.set_printoptions(suppress=True)
    from mvpa2.testing.datasets import *
    ds_test = datasets['uni2medium']
    cv_results = cv(ds_test)
    print clf.ca.estimates
    print np.exp(clf.ca.estimates)
    [[ inf  inf]
     [ inf  inf]
     [ inf  inf]
     ..., 
     [ inf  inf]
     [ inf  inf]
     [ inf  inf]]
    [[ inf  inf]
     [ inf  inf]
     [ inf  inf]
     ..., 
     [ inf  inf]
     [ inf  inf]
     [ inf  inf]]
    [[ -0.01944892  -3.94967242]
     [ -0.00076531  -7.17560599]
     [ -0.00001929 -10.85568058]
     ..., 
     [-13.5544698   -0.0000013 ]
     [-17.34696917  -0.00000003]
     [ -8.94213108  -0.00013077]]
    [[ 0.98073899  0.01926101]
     [ 0.99923498  0.00076502]
     [ 0.99998071  0.00001929]
     ..., 
     [ 0.0000013   0.9999987 ]
     [ 0.00000003  0.99999997]
     [ 0.00013076  0.99986924]]

**Comment by yarikoptic** [comment] 2018-04-30 17:31
quick one for now (indeed we should track those nan/infs), but here is what I see and my adjusted script (to avoid full suite import):
```shell
$> cat trash/gnb-prob.py
#from mvpa2.suite import *
import os
import numpy as np

from mvpa2.datasets.sources.native import load_tutorial_data
from mvpa2.clfs.gnb import GNB
from mvpa2.measures.base import CrossValidation
from mvpa2.generators.partition import NFoldPartitioner
from mvpa2.mappers.zscore import zscore
from mvpa2.mappers.detrend import poly_detrend
from mvpa2.datasets.miscfx import remove_invariant_features
from mvpa2.testing.datasets import *

datapath = '/usr/share/data/pymvpa2-tutorial/'
haxby = load_tutorial_data(datapath,
        roi='vt',
        add_fa={'vt_thr_glm': os.path.join(datapath, 'haxby2001',
                                           'sub001', 'masks',
                                                     'orig', 'vt.nii.gz')})
#poly_detrend(haxby, polyord=1, chunks_attr='chunks')
haxby = haxby[np.array([l in ['rest', 'house', 'face']
                           for l in haxby.targets], dtype='bool')]
zscore(haxby, chunks_attr='chunks', param_est=('targets', ['rest']), dtype='float32')
haxby = haxby[haxby.sa.targets != 'rest']
haxby = remove_invariant_features(haxby)

clf = GNB(enable_ca='estimates', logprob=True, normalize=True)

cv = CrossValidation(clf, NFoldPartitioner(attr='chunks'), postproc=None, enable_ca=['stats'])

for ds in haxby, datasets['uni2medium']:
    print ds
    cv_results = cv(ds)
    print "Estimates:\n", clf.ca.estimates
    print "Exp(estimates):\n", np.round(np.exp(clf.ca.estimates), 3)

$> MVPA_SEED=1 PYTHONPATH=$PWD python trash/gnb-prob.py
WARNING: Detected incorrect (nan) scl_ fields. Resetting to scl_slope=1.0 and scl_inter=0.0
 * Please note: warnings are printed only once, but underlying problem might occur many times *
<Dataset: 216x577@float32, <sa: chunks,run,subj,targets,task,time_coords,time_indices>, <fa: voxel_indices,vt_thr_glm>, <a: imgaffine,imghdr,imgtype,mapper,voxel_dim,voxel_eldim>>
/home/yoh/proj/pymvpa/pymvpa/mvpa2/clfs/gnb.py:275: RuntimeWarning: divide by zero encountered in log
  prob_cs_cp -= np.log(prob_s_cp_marginals)
Estimates:
[[             inf              inf]
 [ -1.77074217e+02   1.60412128e-09]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [             inf              inf]
 [  0.00000000e+00  -3.52226674e+02]
 [  0.00000000e+00  -3.68336864e+02]
 [  0.00000000e+00  -3.53951868e+02]
 [  0.00000000e+00  -4.05223624e+02]
 [  5.22959454e-12  -3.92505031e+02]
 [             inf              inf]
 [             inf              inf]
 [ -5.13105078e-08  -3.79362403e+02]]
Exp(estimates):
[[ inf  inf]
 [  0.   1.]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [ inf  inf]
 [  1.   0.]
 [  1.   0.]
 [  1.   0.]
 [  1.   0.]
 [  1.   0.]
 [ inf  inf]
 [ inf  inf]
 [  1.   0.]]
<Dataset: 48x14@float64, <sa: chunks,targets,train>, <fa: nonbogus_targets>, <a: bogus_features,lastpartitionset,nonbogus_features,train_set>>
Estimates:
[[ -5.42750499e-06  -1.21240337e+01]
 [ -7.48240756e-01  -6.40931068e-01]
 [ -8.50306438e-04  -7.07033888e+00]
 [ -3.38129745e-04  -7.99224993e+00]
 [ -4.71164602e+00  -9.03062130e-03]
 [ -9.02200123e+00  -1.20731575e-04]
 [ -5.54401130e+00  -3.91847513e-03]
 [ -3.07911621e+00  -4.70914955e-02]]
Exp(estimates):
[[ 1.     0.   ]
 [ 0.473  0.527]
 [ 0.999  0.001]
 [ 1.     0.   ]
 [ 0.009  0.991]
 [ 0.     1.   ]
 [ 0.004  0.996]
 [ 0.046  0.954]]
MVPA_SEED=1 PYTHONPATH=$PWD python trash/gnb-prob.py  6.42s user 1.37s system 93% cpu 8.357 total
```

**Comment by dinga92** [comment] 2018-04-30 18:16
So it is indeed a bug? Those perfect 1 and 0 also looks suspicious for probabilities

**Comment by dinga92** [comment] 2018-04-30 23:47
it seems like the cause is numeric underflow at line 270 and 273 in gnb.py. Very negative logprobs are exponentiated before normalizing, which makes them basically 0 which then creates nans or infs if division by 0, or it just does not normalize it correctly, thus producing bogus probs that do not sum to 1.

    if params.normalize:
            if params.logprob:
                prob_cs_cp_real = np.exp(prob_cs_cp)
            else:
                prob_cs_cp_real = prob_cs_cp
            prob_s_cp_marginals = np.sum(prob_cs_cp_real, axis=0)
            if params.logprob:
                prob_cs_cp -= np.log(prob_s_cp_marginals)
            else:
                prob_cs_cp /= prob_s_cp_marginals

which can be fixed by changing the respective lines to

    prob_s_cp_marginals = np.sum(prob_cs_cp, axis=0) #suming logs to avoid underflow
    prob_cs_cp /= prob_s_cp_marginals

not sure about the algebra of the whole situation, but it seems to work. I can send a PR with a fix. Any idea for a test that can capture this?

**Comment by yarikoptic** [comment] 2018-05-01 00:11
Underflow happens even earlier. Your change is identical to already existing code if not params.logprob, it what an I missing?

**Comment by yarikoptic** [comment] 2018-05-01 03:09
so -- let me just ask first -- why do you want "raw" probabilities, and either you observe them to degenerate in your real data in searchlight (where you would have less features so products might stay "sane").

The reason for overflow if operating in non-log space is `prob_csf.prod(axis=2)` so with haxby data it is a product of >500 of smaller than 1 numbers which "annihilate" themselves into 0.  We could probably research how others do it and see if we could come up with deducing some scaling so we keep exponent from exploding.  But it would be nice to know that the effort is worthwhile

if you see a better solution -- let me know ;-)

**Comment by dinga92** [comment] 2018-05-01 06:42
> Underflow happens even earlier. Your change is identical to already existing code if not params.logprob, it what an I missing?

in the existing code, it is summing probabilities (not logprobs), which are small and underflow, regardless of params.logprob. If params.logprob, then they are first exponentiated and they undeflow, and if not params.logprob, then they are already probabilitites, so they don't have to be exponentiated.

My change would sum logprobs instead of probs, which right now is the opposite, thus avoiding underflow, and the real probabilities are produced only after they are normalized.

**Comment by dinga92** [comment] 2018-05-01 07:03
> so -- let me just ask first -- why do you want "raw" probabilities,

maybe we can have params if the user would prefer underflow or overflow :)
I want to have raw probabilities, so error measures other than accuracy are valid. I see that GNB searchlight is outputing already thresholded predicitons  (class with the highest probability), so if I would like to compute something like AUC, or MSE instead of of just proportion of correct matches, it cannot be done, and the result is misleading.

In between subject clf, you need around 60% more subjects using accuracy to get the same power as with alternative measures. I suppose this would also be the case with searchlight, which would be a reason enough to get well-behaved probabilities. I am just writing a report showing exactly this, and trying to complement it with searchlight analysis using a different error measure. I need something fast and probabilistic in order to do that.

**Comment by dinga92** [comment] 2018-05-01 07:10
it's hard to say if it breaks with SL as well, because gnb sl does not have this option yet, but in the haxby exmaple dataset, it starts to underflow somewhere around 100-150 voxels.

**Comment by yarikoptic** [comment] 2018-05-01 16:39
I guess if you just `ds.samples *= 5` or so after the zscoring, you might avoid underflow for more ;)

**Comment by dinga92** [comment] 2018-05-02 14:53
Wouldn't it be the same right after it fits the gaussian? Anyway, the fix I talked about worked for me and i've got my SL probabilities. I am getting 40-70% more significant voxels using probability based errors compared to accuracy, so I think it would be worth it to implement it properly.

**Closed** 2019-05-22 14:55 UTC
